# Generated by Django 3.0.5 on 2020-04-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mogu', models.CharField(max_length=128)),
                ('lajiao', models.CharField(max_length=128)),
                ('jidan', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zhishi', models.CharField(max_length=128)),
                ('toppings', models.ManyToManyField(to='myapp.Topping')),
            ],
        ),
    ]
