# Generated by Django 3.0.5 on 2020-04-18 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topping',
            old_name='jidan',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='topping',
            old_name='lajiao',
            new_name='weidao',
        ),
        migrations.RemoveField(
            model_name='topping',
            name='mogu',
        ),
    ]
