# Generated by Django 3.0.5 on 2020-04-19 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200419_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topping',
            options={'verbose_name': '名称', 'verbose_name_plural': '名称'},
        ),
    ]
