# Generated by Django 3.0.5 on 2020-04-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200419_2044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topping',
            options={},
        ),
        migrations.AlterField(
            model_name='topping',
            name='name',
            field=models.CharField(max_length=128, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='topping',
            name='weidao',
            field=models.CharField(max_length=128, verbose_name='味道'),
        ),
    ]
