# Generated by Django 3.0.5 on 2020-04-19 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200419_2053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topping',
            options={'verbose_name': '浇头名', 'verbose_name_plural': '浇头名'},
        ),
        migrations.AlterModelTable(
            name='topping',
            table='浇头',
        ),
    ]
